[package]

name = "x86"
version = "0.5.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>", "Eric Kidd <git@randomhacks.net>"]

description = "Library to program x86 (amd64) hardware. Contains x86 specific data structure descriptions, data-tables, as well as convenience function to call assembly instructions typically not exposed in higher level languages."

homepage = "https://github.com/gz/rust-x86"
repository = "https://github.com/gz/rust-x86"
documentation = "http://gz.github.io/rust-x86/x86/"
readme = "README.md"
keywords = ["ia32", "os", "amd64", "x86", "x86-64"]
license = "MIT"
build = "build.rs"

[[test]]
name = "no_std_build"
harness = false

[build-dependencies]
phf_codegen = "0.7.7"
csv = "0.14.3"
serde_json = "0.6.0"

[dependencies.raw-cpuid]
git = "https://github.com/smkell/rust-cpuid.git"

[dependencies.phf]
git = "https://github.com/smkell/rust-phf.git"
features = ["use_core"]

[target.x86_64-unknown-none-gnu.dependencies.core]
git = "https://github.com/phil-opp/nightly-libcore.git"
features = [ "disable_float" ]
